name: Performance Tests

on: [push, pull_request]

jobs:
  jmeter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run JMeter
        run: |
          sudo apt-get update && sudo apt-get install -y jmeter
          jmeter -n -t performance-tests/load_test.jmx -l performance-tests/results.jtl -e -o performance-tests/reports
      - uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: performance-tests/reports