name: Security Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          # Alvo público e correto (seu site)
          target: 'https://pedroviena.com'
          
          # Nome do artefato corrigido
          artifact_name: 'zap_report'