name: Security Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://pedroviena.com'
          
          # CORREÇÃO: Alterado o nome do artefato para usar underscore,
          # que é um caractere mais seguro para nomes de artefatos.
          artifact_name: 'zap_report'