name: Security Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://pedroviena.com'
 
          report_name: 'zap_report'

      - name: Upload ZAP Report
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report 
          path: zap_report.html 