name: Security Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    permissions:
      # Concede permissão de escrita para Issues, resolvendo o erro de acesso
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          # Lembre-se de substituir pela URL do seu ambiente de testes real
          target: 'https://pedroviena.com'
          artifact_name: 'zap-report'